# Generated by Django 5.0.6 on 2024-07-29 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expert_FIO', models.CharField(max_length=100, verbose_name='ФИО')),
                ('expert_company', models.CharField(max_length=100, verbose_name='Организация')),
                ('expert_direction', models.CharField(max_length=100, verbose_name='Направление')),
                ('expert_country', models.CharField(max_length=60, verbose_name='Страна')),
                ('expert_phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('expert_email', models.CharField(max_length=30, verbose_name='Почта')),
                ('expert_about', models.TextField(verbose_name='О себе')),
                ('expert_photo', models.ImageField(blank=True, upload_to='images/experts', verbose_name='Фото')),
            ],
        ),
    ]
