# Generated by Django 5.0.6 on 2024-07-29 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expert',
            options={'verbose_name': 'Эксперт', 'verbose_name_plural': 'Эксперты'},
        ),
    ]
