# Generated by Django 5.0.6 on 2024-07-30 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0003_alter_expert_expert_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='expert_photo',
            field=models.ImageField(blank=True, upload_to='images/experts', verbose_name='Фото'),
        ),
    ]
