# Generated by Django 5.0.6 on 2024-08-04 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0006_news_alter_expert_expert_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='expert_chapter',
            field=models.CharField(max_length=50, null=True, verbose_name='Раздел'),
        ),
    ]
