# Generated by Django 5.0.6 on 2024-08-05 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0007_expert_expert_chapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='expert_chapter',
            field=models.CharField(choices=[('Бизнес', 'Бизнес'), ('Право', 'Право'), ('Творчество', 'Творчество'), ('Волонтерство', 'Волонтерство'), ('Наука', 'Наука')], max_length=50, null=True, verbose_name='Раздел'),
        ),
    ]
