# Generated by Django 5.0.6 on 2024-08-06 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0009_alter_news_news_chapter'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertsMean',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mean_heading', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('mean_content', models.TextField(verbose_name='Содержание')),
                ('mean_likes', models.IntegerField(default=0, verbose_name='Лайки')),
                ('mean_photo', models.ImageField(blank=True, upload_to='images/ExpertMean', verbose_name='Фото')),
                ('mean_chapter', models.CharField(choices=[('Бизнес', 'Бизнес'), ('Право', 'Право'), ('Творчество', 'Творчество'), ('Волонтерство', 'Волонтерство'), ('Наука', 'Наука')], max_length=50, null=True, verbose_name='Раздел')),
                ('expert_fio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='experts.expert')),
            ],
        ),
    ]
