# Generated by Django 5.0.6 on 2024-08-06 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0010_expertsmean'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expertsmean',
            options={'verbose_name': 'Мнение эксперта', 'verbose_name_plural': 'Мнения экспертов'},
        ),
    ]
