# Generated by Django 5.0.6 on 2024-08-13 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0011_alter_expertsmean_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_chapter', models.CharField(choices=[('Бизнес', 'Бизнес'), ('Право', 'Право'), ('Творчество', 'Творчество'), ('Волонтерство', 'Волонтерство'), ('Наука', 'Наука')], max_length=50, null=True, verbose_name='Раздел')),
                ('state_heading', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('state_short_description', models.CharField(max_length=200, verbose_name='Краткое описание')),
                ('state_content', models.TextField(verbose_name='Содержание')),
                ('state_photo', models.ImageField(blank=True, upload_to='images/State', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
    ]
