# Generated by Django 5.0.6 on 2024-08-20 08:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0012_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjecPar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100, null=True, verbose_name='Наименование')),
                ('project_photo', models.ImageField(blank=True, upload_to='images/Project', verbose_name='Логотип')),
                ('project_text', models.TextField(verbose_name='Содержание')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Мероприятие', 'verbose_name_plural': 'Мероприятия'},
        ),
        migrations.RemoveField(
            model_name='expertsmean',
            name='mean_chapter',
        ),
        migrations.RemoveField(
            model_name='expertsmean',
            name='mean_likes',
        ),
        migrations.RemoveField(
            model_name='news',
            name='news_chapter',
        ),
        migrations.AddField(
            model_name='expertsmean',
            name='mean_video',
            field=models.FileField(default=django.utils.timezone.now, upload_to='images/video', verbose_name='Видео'),
            preserve_default=False,
        ),
    ]
