# Generated by Django 5.0.6 on 2024-08-20 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0014_remove_news_news_short_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expert',
            name='id',
        ),
        migrations.AlterField(
            model_name='expert',
            name='expert_FIO',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='ФИО'),
        ),
    ]
